name: Publish

on:
  push:
    tags:
      - '*.*.*'

jobs:
  publish:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: Packaging
      shell: pwsh
      run: ./package.ps1
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: 'package/MMAccel_*.zip'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
